#!/usr/bin/env bash
#This script displays information about my domain names.

func () {
	if [ $# -eq 1 ]; then
		dig "www.$1" +noall +answer | awk '{print "The subdomain www is a "$4" record and points to "$5""}'
		dig "lb-01.$1" +noall +answer | awk '{print "The subdomain lb-01 is a "$4" record and points to "$5""}'
		dig "web-01.$1" +noall +answer | awk '{print "The subdomain web-01 is a "$4" record and points to "$5""}'
		dig "web-02.$1" +noall +answer | awk '{print "The subdomain web-02 is a "$4" record and points to "$5""}'
	elif [ "$2" ]; then
		subdomain=$2
		dig "$subdomain.$1" +noall +answer | awk -v subdom="$subdomain" '{print "The subdomain " subdom " is a "$4" record and points to "$5""}'
	fi
}

func $1 $2
