#!/usr/bin/env bash
# This contains the script for installing the nginx server
sudo apt update
sudo apt -y install nginx
sudo chown -R $USER:$USER /var/www/html
echo 'Hello World!' > /var/www/html/index.html
sudo chown -R root:root /var/www/html
sudo service nginx restart
