#!/usr/bin/env bash
#Bash script to debug a web stack

#Update the apt package and install nginx
sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-avaialable/default /etc/nginx/sites-enabled

#sudo apt-get -y install nginx

#Start the nginx service
sudo service nginx start
