#!/usr/bin/env bash
#command to echo infinity and beyond
sudo sh -c 'echo $$ > /var/run/myscript.pid'
trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y u no love me?!'" SIGINT
trap "sudo rm /var/run/myscript.pid" SIGQUIT SIGTERM
i=0
while [ "$i" -eq 0 ]; do
	echo "To infinity and beyond"
	sleep 2
done
