#!/usr/bin/env bash
#command to echo infinity and beyond
echo $$ | sudo tee /var/run/myscript.pid >/dev/null
trap 'echo "I hate the kill command"; sudo rm /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y u no love me?!"' SIGINT
trap 'sudo rm /var/run/myscript.pid; exit' SIGQUIT
i=0
while [ "$i" -eq 0 ]; do
	echo "To infinity and beyond"
	sleep 2
done
