#!/usr/bin/env bash
#Script to run nginx as nginx
chown nginx:nginx /etc/init.d/nginx /var/log/nginx
chown -R nginx:nginx /etc/nginx
su -c "chmod -R u=rwx,g=rwx /etc/nginx" nginx
new_string='listen 8080 default_server;'
old_string='listen 80 default_server;'
new_string1='listen \[::\]:8080 default_server ipv6only=on;'
old_string1='listen \[::\]:80 default_server ipv6only=on';
sed -i "s/$old_string/$new_string/" /etc/nginx/sites-available/default
sed -i "s/$old_string1/$new_string1/" /etc/nginx/sites-available/default
pkill -9 apache2
su -c "/etc/init.d/nginx start" nginx
